"""Add 5 harder questions per work + fix MCQ progress tracking."""
import re

with open(r'C:/Users/Muhanad/Desktop/AS2_Revision/index.html', encoding='utf-8') as f:
    content = f.read()

# ── FIX 1: updateUI — compute MCQ progress from topic bests ──────────────────
OLD_UPDATE_UI_MCQ = """  const mcqBest = progress.mcq.highScore;
  const mcqAttempts = progress.mcq.attempts;

  // sidebar badges
  setBadge('badge-works', `${wDone}/6`, wDone === 6);
  setBadge('badge-schools', `${sDone}/5`, sDone === 5);
  setBadge('badge-terms', `${tDone}/${tTotal}`, tDone === tTotal);
  setBadge('badge-mcq', mcqAttempts > 0 ? `${mcqBest}%` : '0%', mcqBest === 100);
  setBadge('badge-essay', `${progress.essay.viewed.length}/3`, progress.essay.viewed.length === 3);
  setBadge('badge-quoteid', `${progress.quoteId.correct}/${progress.quoteId.total || 14}`, false);

  // home stats
  setText('stat-works', `${wDone}/6`);
  setText('stat-terms', `${tDone}/${tTotal}`);
  setText('stat-mcq', mcqAttempts > 0 ? `${mcqBest}%` : '–');

  // jump badges
  setText('jbadge-works', `${wDone} of 6 completed`);
  setText('jbadge-schools', `${sDone} of 5 completed`);
  setText('jbadge-terms', `${tDone} of ${tTotal} learned`);
  setText('jbadge-mcq', mcqAttempts > 0 ? `Best: ${mcqBest}%` : 'Not started');"""

NEW_UPDATE_UI_MCQ = """  // MCQ progress = average of best scores across all 11 topics (unplayed = 0)
  const ALL_TOPIC_IDS = ['tbf','tob','dochill','abel','cory','mill','naturalism','impressionism','realism','modernism','regionalism'];
  const topicBests = progress.topicBests || {};
  const mcqAttempted = ALL_TOPIC_IDS.filter(id => topicBests[id] != null).length;
  const mcqAvg = mcqAttempted > 0
    ? Math.round(ALL_TOPIC_IDS.reduce((sum, id) => sum + (topicBests[id] || 0), 0) / ALL_TOPIC_IDS.length)
    : 0;
  const mcqBest = mcqAvg;
  const mcqAttempts = mcqAttempted;

  // sidebar badges
  setBadge('badge-works', `${wDone}/6`, wDone === 6);
  setBadge('badge-schools', `${sDone}/5`, sDone === 5);
  setBadge('badge-terms', `${tDone}/${tTotal}`, tDone === tTotal);
  setBadge('badge-mcq', mcqAttempts > 0 ? `${mcqBest}%` : '0%', mcqBest >= 90);
  setBadge('badge-essay', `${progress.essay.viewed.length}/3`, progress.essay.viewed.length === 3);
  setBadge('badge-quoteid', `${progress.quoteId.correct}/${progress.quoteId.total || 14}`, false);

  // home stats
  setText('stat-works', `${wDone}/6`);
  setText('stat-terms', `${tDone}/${tTotal}`);
  setText('stat-mcq', mcqAttempts > 0 ? `${mcqBest}%` : '–');

  // jump badges
  setText('jbadge-works', `${wDone} of 6 completed`);
  setText('jbadge-schools', `${sDone} of 5 completed`);
  setText('jbadge-terms', `${tDone} of ${tTotal} learned`);
  setText('jbadge-mcq', mcqAttempts > 0 ? `Avg: ${mcqBest}% (${mcqAttempts}/11 topics)` : 'Not started');"""

if OLD_UPDATE_UI_MCQ in content:
    content = content.replace(OLD_UPDATE_UI_MCQ, NEW_UPDATE_UI_MCQ)
    print('OK: updateUI MCQ progress fixed')
else:
    print('MISS: updateUI MCQ block not found')

# ── FIX 2: endTopicQuiz — remove the highScore mutation ──────────────────────
OLD_END = """  // update overall mcq tracking for home bar
  if (pct > (progress.mcq.highScore || 0)) { progress.mcq.highScore = pct; }
  progress.mcq.attempts = (progress.mcq.attempts || 0) + 1;"""

NEW_END = """  // mcq overall progress is now derived from topicBests in updateUI — no manual highScore needed"""

if OLD_END in content:
    content = content.replace(OLD_END, NEW_END)
    print('OK: endTopicQuiz highScore mutation removed')
else:
    print('MISS: endTopicQuiz highScore block not found')

# ── FIX 3: home bar color — green at >=90 avg ────────────────────────────────
# setBar for mcq uses mcqBest which is now the average — no change needed to color logic
# The bar fill color is CSS class home-bar-mcq, already green. The amber issue was
# because mcqBest=100 from one topic but setBar just sets width. Let me check updateHomeBars.
# Actually the amber issue is likely the bar itself — let me just verify no color logic there.

# ── ADD 5 HARDER QUESTIONS PER WORK ──────────────────────────────────────────

TBF_EXTRA = """      { q: 'The man builds a first fire successfully, but snow falls from a spruce tree and extinguishes it. In a Naturalist reading, the narrative function of this event is:', options: ['It shows the man\'s poor fire-placement judgment and carelessness', 'Even when the man acts correctly, indifferent environmental forces can nullify his actions — the outcome is not determined by competence but by conditions beyond control', 'It foreshadows that he will learn from this mistake and eventually survive', 'It creates dramatic tension by giving the reader temporary hope'], correct: 1, explanation: 'The first fire is correctly built — but nature extinguishes it anyway. Naturalism\'s point: competence is irrelevant when environmental forces operate indifferently. Doing the right thing offers no guarantee.' },
      { q: 'London writes: "The trouble with him was that he was without imagination." This sentence most directly identifies the man\'s fatal flaw as:', options: ['Determinism — his fate was sealed by environmental conditions before the story began', 'Impressionism — he lacks the subjective perceptive capacity to feel danger', 'His inability to imagine danger he hasn\'t yet experienced — he cannot feel what he doesn\'t currently perceive, so he rationalizes continuing despite clear warning signs', 'Naturalism — London suggests humans are governed by biology rather than imagination'], correct: 2, explanation: 'Imagination here means the capacity to project beyond immediate experience — to feel the danger of -75°F without having yet felt his hands freeze. The man can know facts about cold but cannot imagine their consequence. This gap kills him.' },
      { q: 'Near the story\'s end, the man considers killing the dog to warm his hands in its body heat. He cannot act on this because his hands are too frozen to hold his knife. What does this episode most directly demonstrate?', options: ['His moral conscience prevents him from harming the dog', 'The dog\'s loyalty and instinct protect it from the man\'s desperation', 'Nature has removed even his last potential survival action — not through his choice but through physical deterioration beyond his control', 'The man has accepted that he cannot survive and stops trying'], correct: 2, explanation: 'The cruelest Naturalist irony: the man thinks of a way to survive, but his body\'s deterioration — a condition entirely outside his control — makes the action impossible. Even his final idea is foreclosed by environment, not will.' },
      { q: 'London spends several paragraphs establishing the precise science of cold — how spit freezes before hitting the ground, how exposed flesh freezes in seconds at -75°F. What is the primary narrative function of this scientific precision?', options: ['It establishes London\'s credibility as a Yukon survival expert', 'It creates scientific authority that makes the environment an objective, impersonal force — reinforcing Naturalism\'s idea that nature operates by fixed, indifferent laws that do not bend for human presence', 'It is Realism — London depicts the cold accurately without romanticizing', 'It foreshadows the specific physical failures the man will experience'], correct: 1, explanation: 'The scientific detail makes nature feel like a system, not a character. It operates by fixed laws — temperature, biology, physics — that are utterly indifferent to the man\'s presence. The precision reinforces Naturalist determinism: these are conditions, not choices.' },
      { q: 'At the story\'s end, the man achieves what London calls a "new picture of himself" — he imagines his own death with calm acceptance. This moment is most significant because:', options: ['It shows the man has finally achieved wisdom, though too late to act on it', 'It is a Naturalist endpoint — his rational mind finally surrenders to the reality that physical conditions have determined his fate; intelligence cannot alter what environment has decided', 'It is Impressionism — the man\'s subjective perception shifts in his final moments', 'It represents the emotional climax and humanizes a previously flat protagonist'], correct: 1, explanation: 'The calm acceptance is not peace — it is the exhaustion of intelligence against determinism. The man\'s mind finally stops trying to solve the unsolvable. London\'s Naturalism: the outcome was always determined; the man just took the whole story to stop arguing with it.' }"""

TOB_EXTRA = """      { q: 'The four men develop intense brotherhood through their shared ordeal. Yet Crane ends the story by drowning the most capable of them. What does this tension between human solidarity and Naturalist outcome argue?', options: ['Crane valued brotherhood over survival and considered it a moral victory even in death', 'Human bonds are real and meaningful, but they cannot override the indifferent operations of natural force — Naturalism coexists with the value of human connection without being defeated by it', 'Crane was critiquing the idea that cooperation leads to survival in dangerous situations', 'The oiler\'s death was accidental — he should have conserved energy during the rowing'], correct: 1, explanation: 'Crane doesn\'t deny the reality or value of the men\'s bond. He simply shows that nature doesn\'t register it. Human solidarity is real; Naturalist indifference is also real. Both are true simultaneously — and the oiler dies anyway.' },
      { q: 'During the night watch, the correspondent suddenly feels profound sympathy for a dying soldier in a poem he memorized as a child but never cared about. What does this episode most precisely illustrate about Impressionism?', options: ['The correspondent is delirious from exhaustion and confusion', 'Impressionism shows how proximity to death creates false or exaggerated emotions', 'Lived experience reshapes perception — the correspondent can now feel what he once only knew intellectually because his own crisis has opened him to the subjective reality of suffering', 'The episode is foreshadowing — the dying soldier poem predicts Billie\'s death'], correct: 2, explanation: 'The correspondent knew the poem\'s words but they meant nothing. Now, facing death himself, those words detonate with feeling. Impressionism: subjective experience reshapes what can be perceived and felt. The same words, a completely different inner event.' },
      { q: 'Crane uses the phrase "the brotherhood of men" to describe the crew\'s bond, then immediately has nature kill Billie. What literary device does this juxtaposition most precisely create?', options: ['Symbolism — the sea represents both life and death simultaneously', 'Irony — warm language of human brotherhood is immediately undercut by Naturalist indifference, exposing the gap between human meaning-making and nature\'s actual operations', 'Foreshadowing — "brotherhood" signals that someone will sacrifice themselves for the group', 'Understatement — Crane softens the blow of the oiler\'s death with warm language beforehand'], correct: 1, explanation: 'Crane uses the language of human meaning (brotherhood) then demolishes it with natural indifference (Billie\'s death). The juxtaposition is ironic — it exposes how human frameworks of meaning crash against Naturalism\'s indifferent reality.' },
      { q: '"When it occurs to a man that nature does not regard him as important... he at first wishes to throw bricks at the temple." What does the correspondent\'s anger reveal about Naturalism as a lived experience vs. a philosophical framework?', options: ['Naturalism is an intellectual framework, but living inside it — facing actual death at nature\'s indifference — produces rage and the desperate search for meaning that the philosophy itself says doesn\'t exist', 'The correspondent doesn\'t understand Naturalism and mistakenly believes the universe owes him an explanation', 'The anger is a survival signal — those who fight emotionally are the ones who survive', 'Crane is critiquing Naturalism here by showing the correspondent\'s anger is philosophically justified'], correct: 0, explanation: 'Naturalism as a philosophy says: nature is indifferent, outcomes are determined. Naturalism as a lived experience produces fury at that indifference. Crane captures both — the correspondent knows there\'s no answer and still demands one. The rage is human; the silence is Naturalist.' },
      { q: 'The story\'s final sentence describes the ocean\'s waves and "the great sea\'s voice" rather than the survivors\' relief or grief. Why does Crane end on nature\'s voice?', options: ['Crane is showing that the ocean is beautiful despite its danger, offering a final note of reconciliation', 'Ending on nature\'s voice rather than human emotion reinforces the Naturalist point — the sea continues unchanged by the men\'s ordeal or Billie\'s death; it does not register what happened; human events leave no mark on it', 'The ocean\'s voice symbolizes the bond the survivors now permanently share with the sea', 'Crane ends on the ocean to create peaceful resolution and emotional closure after the trauma'], correct: 1, explanation: 'Crane\'s last move is his most Naturalist: the story ends not with human response but with the sea\'s indifferent continuation. The ocean doesn\'t know Billie died. It doesn\'t know any of it happened. Nature\'s voice, not human grief, is the final word.' }"""

DOCHILL_EXTRA = """      { q: 'Doc Hill speaks directly from the grave; Richard Cory is narrated by the townspeople. Contrast what each narrative choice reveals about its subject.', options: ['Doc Hill\'s self-narration reveals what the community saw; Cory\'s community narration reveals what he felt inside', 'Doc Hill\'s self-narration gives direct access to his values and choices; Cory\'s community narration reveals only surface appearance — the community never accessed Cory\'s inner life, which is the poem\'s tragic point', 'Both poems use the same perspective — first-person retrospective voice', 'Community narration in Richard Cory is more reliable because multiple witnesses confirm the same observations'], correct: 1, explanation: 'The contrast is the point. Doc Hill tells us who he was directly — his values, his choices, his self-assessment. Cory\'s community can only tell us what he looked like. Robinson\'s formal choice in Richard Cory performs the tragedy: nobody could access Cory\'s inner life.' },
      { q: 'In a Spoon River Anthology full of people who accumulated, competed, and failed quietly, Doc Hill\'s service stands as a counter-argument. What is Masters arguing about community, individual meaning, and how a life gets remembered?', options: ['That professional service is the only truly meaningful way to live a life', 'Individual meaning is created through contribution to the community — giving to others is what makes a life coherent and remembered with love rather than pity or indifference', 'Economic hardship in small-town America made generosity the only viable path for some people', 'Doctors occupy a uniquely virtuous position in American social life that other occupations cannot achieve'], correct: 1, explanation: 'Masters uses Doc Hill as the positive term in a contrast. Abel is remembered with pity; Doc Hill is remembered with love. The difference is giving vs. accumulating. Masters\' argument: meaning is built outward, not collected inward.' },
      { q: 'Doc Hill and Abel Melveny exist in the same small town in Spoon River Anthology. What is the literary effect of placing these two characters as neighbors in the same community?', options: ['It establishes realistic diversity of occupations in small-town American life', 'It creates an implicit argument through contrast — the reader encounters both characters as neighbors, forcing a direct comparison of two ways of living and two different outcomes for how a life is remembered', 'It is a coincidental feature of setting — the characters have no meaningful relationship to each other', 'It creates Regionalist local color by depicting multiple trades within the same community'], correct: 1, explanation: 'The Anthology\'s structure is the argument. Doc Hill and Abel aren\'t isolated poems — they\'re neighbors. Reading them together forces the comparison: action and giving (Doc Hill) vs. accumulation and regret (Abel). Masters built the argument into the collection\'s architecture.' },
      { q: 'Doc Hill\'s poem describes no single dramatic event — just a quiet accumulation of acts of service over a lifetime. Why does Masters choose this undramatic mode of presentation for an admirable character?', options: ['Masters was not skilled at writing dramatic scenes or emotional peaks', 'Consistent with Realism, Masters presents admirable lives without heroizing — Doc Hill\'s greatness is in the ordinary accumulation of small acts; dramatizing it would falsify it by implying greatness requires a single heroic moment', 'The poem\'s quietness reflects Doc Hill\'s personal modesty and his own self-assessment', 'Masters uses understatement to avoid sentimentality about a character he personally admired deeply'], correct: 1, explanation: 'Realism: ordinary lives depicted honestly, without heroic framing. Doc Hill\'s goodness was built act by act, patient by patient, over decades. A dramatic climax would lie about what that kind of life looks like. Masters\' quietness is its own argument.' },
      { q: 'The dead-speaker form means Doc Hill cannot be questioned or contradicted. Yet Masters makes him entirely self-critical and honest about his limits. What does this self-critical honesty achieve that a living narrator\'s praise could not?', options: ['It makes Doc Hill appear more intellectually sophisticated and self-aware', 'Because the dead have nothing to lose or gain, Doc Hill\'s honest self-assessment carries complete credibility — we believe him entirely because his motives for distortion are gone; self-praise from the dead has no agenda', 'It allows Masters to insert his own authorial judgment through Doc Hill\'s voice indirectly', 'It creates dramatic irony since readers know more than Doc Hill about how his community remembered him'], correct: 1, explanation: 'The dead have nothing to gain from flattery and nothing to lose from honesty. When Doc Hill assesses his own life critically, we believe it completely — there is no social performance left, no career to protect. The form makes the honesty structurally inevitable.' }"""

ABEL_EXTRA = """      { q: 'Abel Melveny lists his unused machines in accumulating detail across the poem. As a rhetorical device, what does this extended catalogue accomplish that a simple statement ("Abel collected many machines") could not?', options: ['It provides historical documentation of what machines existed in the period', 'The catalogue form performs Abel\'s problem — the endless accumulation of objects mirrors the endless accumulation of unused intentions; the reader feels the weight and absurdity of a life of plans without action', 'It creates Realist specificity by naming the actual machines of the era', 'It is dramatic irony — the reader knows these machines represent regret before Abel explicitly admits it'], correct: 1, explanation: 'The list is the argument. It keeps going — machine after machine — and the reader starts to feel what Abel never allowed himself to feel: this is ridiculous. This is a life. The catalogue form makes the reader experience the accumulation before Abel names it as regret.' },
      { q: 'Abel Melveny and the miller in "The Mill" both die with potential unrealized. One dies due to external industrial forces; the other due to a personal behavioral pattern. What does this distinction reveal about how Masters and Robinson differently assign responsibility for a life wasted?', options: ['Masters blames society; Robinson blames the individual exclusively', 'The miller\'s destruction is imposed from outside — industrial obsolescence; Abel\'s regret is self-generated — he had the tools and time but chose accumulation over action; Robinson\'s tragedy is determined externally, Masters\' is self-made', 'Both characters are equally responsible for their fates — they both could have chosen differently', 'Robinson\'s miller is a Naturalist figure destroyed by environment; Abel is a purely Realist figure who failed personally'], correct: 1, explanation: 'This distinction matters. The miller is destroyed by the Industrial Revolution — a force entirely outside his control. Abel had every tool he needed and never acted. Robinson\'s tragedy is imposed; Masters\' tragedy is chosen, which makes it differently devastating.' },
      { q: 'One reading of Abel Melveny is that the machines represented safety precisely because they were never used — an unused machine cannot fail; an unstarted project cannot disappoint. What does this psychological reading add to Masters\' critique?', options: ['It makes Abel more sympathetic but doesn\'t change Masters\' argument about accumulation', 'It deepens Masters\' critique — a life organized around avoiding failure by never starting is not only wasted but actively chosen; Abel\'s accumulation may be self-protection against the risk of action, making the regret more tragic because it was deliberate', 'This reading contradicts the text — Abel clearly intended to use the machines someday', 'Applying Impressionist psychology to a Realist text is methodologically inappropriate'], correct: 1, explanation: 'If Abel feared failure, the machines were perfect: they represented infinite future possibility, never tested against reality. Masters\' critique deepens — Abel wasn\'t just passive; he may have organized his life around the comfort of potential never risked. The machines were the lie he lived by.' },
      { q: 'Spoon River speakers are dead and cannot change their lives. Yet they speak with full awareness of their regrets. What does this structure — complete understanding combined with absolute inability to act — contribute to Abel Melveny\'s emotional power?', options: ['It creates suspense about whether Abel will somehow change even in death', 'The gap between full understanding and permanent inability to act is the poem\'s cruelest irony — Abel sees exactly what was wrong with his life but the moment for correction is permanently past; clarity arrives after the deadline', 'It makes the poem feel like a cautionary tale addressed to the living rather than a genuine character study', 'This structure is unique to Abel Melveny among all the Spoon River poems'], correct: 1, explanation: 'Abel understands everything — the machines, the regret, what he should have done. He understands it with perfect clarity. And he can do absolutely nothing about it. The comprehension without the power to act is Masters\' most devastating formal choice.' },
      { q: 'Abel Melveny is sometimes read as a critique of American materialism — the belief that owning things is equivalent to using them, or that possessing potential is the same as realizing it. If this reading is correct, what does Masters argue about the cultural values of his era?', options: ['That Americans were too focused on industrial progress to develop meaningful personal relationships', 'The equation of ownership with achievement — having tools without using them, having plans without executing them — is a specifically American confusion that Masters targets through Abel\'s regret; possessing potential is not the same as realizing it', 'That Masters was personally and politically opposed to industrialization and private property', 'This reading overreaches — the poem is about one individual\'s psychology, not a cultural critique'], correct: 1, explanation: 'Abel is a case study in American confusion between having and doing, between potential and achievement. Masters lived in an era of boosterism and accumulation — the American dream as property. Abel\'s regret is Masters\' indictment: having without doing is not living.' }"""

CORY_EXTRA = """      { q: 'Robinson denies Richard Cory any direct voice — we never hear his thoughts or feelings. Compare this to Doc Hill, who speaks directly. What does Robinson\'s choice to silence Cory achieve as a formal decision?', options: ['It makes Cory mysterious and romantically unknowable', 'Denying Cory a voice enacts the poem\'s central tragedy — we never know him because nobody knew him; his silence in the narrative mirrors his silence in life; Robinson\'s formal choice makes the poem\'s meaning structural, not just thematic', 'It is a limitation of the first-person plural perspective — "we" can only report what was observed', 'It creates dramatic irony because the reader knows more than the townspeople about Cory\'s inner state'], correct: 1, explanation: 'Robinson could have given Cory even one line of internal thought. He refuses. Cory\'s silence in the poem is the poem\'s argument: nobody got in. The form performs the tragedy — we are locked out exactly as the townspeople were locked out.' },
      { q: 'The townspeople envy Richard Cory throughout the poem — "we wished that we were in his place." After his death, this envy is revealed as built on completely false assumptions. What does Robinson suggest about external social perception?', options: ['That envy is a moral failing the townspeople should have overcome through community values', 'External social perception is structurally unreliable — it can only access surfaces (wealth, appearance, manner) and cannot reach inner experience; the townspeople\'s envy was genuine but based on a fiction constructed from visible signals', 'Richard Cory was deliberately performing contentment to deceive the townspeople around him', 'The townspeople\'s poverty made it structurally impossible for them to imagine that wealthy people could suffer'], correct: 1, explanation: 'The townspeople\'s envy isn\'t a moral failure — it\'s an epistemological one. They could only see surfaces. They constructed "Richard Cory" from visible signals: his manner, his wealth, his grace. They were wrong about the whole structure. Robinson\'s point: social perception is inherently surface-level.' },
      { q: 'Robinson writes: "And Richard Cory, one calm summer night, / Went home and put a bullet through his head." The word "calm" is doing specific work. What is its precise effect?', options: ['It shows Cory was emotionally stable and the suicide was therefore entirely impulsive', '"Calm" denies the reader the dramatic weather they expect — no storm, no visible breakdown; the flatness of the word performs understatement; Robinson makes the point that despair has no visible weather, which is exactly the poem\'s central revelation', '"Calm" describes only the summer night, not Cory\'s state of mind at all', '"Calm" creates irony by contrasting directly with the violence of the suicide described in the same line'], correct: 1, explanation: '"Calm" is the poem\'s most precise word. A calm summer night offers no environmental warning — no pathetic fallacy, no storm to signal catastrophe. Despair doesn\'t announce itself with weather. Robinson removes every external signal so there is no way to have seen it coming. That\'s the point.' },
      { q: 'Some critics argue "Richard Cory" is not primarily about Cory at all — it is about the townspeople and their relationship to wealth, envy, and surface appearances. Evaluate this reading.', options: ['This reading is wrong — Cory is clearly the poem\'s named subject and protagonist', 'This reading has substantial merit: Cory is barely present as an individual; the poem actually depicts the machinery of social envy and projection — how a community constructs an idealized figure from surface signals and discovers the construction was false; Cory is the occasion, but the townspeople\'s blindness is the subject', 'The poem is equally about Cory and the townspeople — both perspectives are balanced throughout', 'This reading is completely correct because Robinson uses "we" to structurally center the townspeople\'s perspective'], correct: 1, explanation: 'Who speaks? The townspeople. What do we get? What they saw — which is everything surface and nothing interior. Cory has one sentence in the whole poem and it describes his appearance. The poem is about the townspeople\'s construction of Cory — their envy, their projection, their blindness. Cory is what they made him.' },
      { q: '"Richard Cory" uses strict ABAB rhyme and regular meter — traditional poetic forms. Yet it is classified as Modernist. How can a poem with traditional formal structure be Modernist in content?', options: ['It cannot — Modernism requires free verse, so the Modernist classification must be incorrect', 'Modernism is primarily a set of concerns (irony, hidden inner lives, disillusionment, gap between surface and reality) not exclusively a formal requirement; Robinson uses orderly conventional form to contain a disillusioned, ironic vision — the tension between controlled form and devastating content is itself a Modernist move', 'Robinson predates Modernism chronologically, so the poem should not be classified as Modernist at all', 'The ABAB rhyme scheme is used ironically throughout, which makes it Modernist despite its conventional appearance'], correct: 1, explanation: 'Modernism is not a form — it is a sensibility. Irony, disillusionment, hidden inner lives, the gap between surface and reality. Robinson\'s use of orderly ABAB for utterly disordered content is its own ironic gesture: the poem looks civilized and controlled; its content is catastrophic. That tension is Modernism.' }"""

MILL_EXTRA = """      { q: '"The Mill" has two deaths — the miller\'s (explicitly stated) and the wife\'s (implied through her walking toward the pond). Why does Robinson choose to show one death directly and leave the other to inference?', options: ['Robinson ran out of space within the poem\'s formal constraints', 'The wife\'s implied death is more devastating than the miller\'s stated death — by leaving it unspoken, Robinson forces the reader to complete the narrative; the ellipsis creates more emotional weight than statement would, making the reader complicit in recognizing the tragedy', 'Robinson intended the wife\'s fate to be genuinely ambiguous — she may survive', 'Showing one death directly and implying the other creates formal structural symmetry'], correct: 1, explanation: 'Robinson says less to force the reader to do more. The wife\'s death, left unstated, requires the reader to assemble the evidence (cold water, walking toward the pond, silence) and arrive at the conclusion themselves. That act of assembly makes the reader feel the death rather than be told it. Narrative ellipsis at its most powerful.' },
      { q: '"The Mill" can be read as a poem about how a man\'s identity can be so fused with his work that when the work dies, he dies. What does this reading suggest about Robinson\'s critique of how society assigns worth to individuals?', options: ['That Robinson believed all workers of this era were too emotionally dependent on their occupations', 'For the miller, his trade was not employment but the structure around which his entire identity was organized — its obsolescence didn\'t just take his income but unmade him as a person; Robinson critiques a society that allows a man\'s worth to be equivalent to his economic function', 'That the Industrial Revolution was economically cruel to individual skilled workers', 'That the miller was psychologically fragile and unable to adapt to the economic changes around him'], correct: 1, explanation: 'The miller had a craft, a role, a place in the world. The Industrial Revolution didn\'t just take his job — it took the thing his selfhood was built around. Robinson\'s critique: a society that equates personhood with economic function makes people fragile in exactly this way. When the function disappears, so does the person.' },
      { q: 'Both "The Mill" and "To Build a Fire" feature protagonists destroyed by forces larger than themselves — one by industrial change, one by nature. Compare the role of determinism in each work.', options: ['Both works show identical determinism — external forces destroy the protagonist regardless of any choice they make', 'London\'s determinism is environmental and biological — the cold is indifferent and determines the physical outcome; Robinson\'s determinism is economic and historical — industrial forces are indifferent and determine the miller\'s obsolescence; both show characters destroyed by systems that don\'t register individual worth, but the deterministic forces differ in kind', '"The Mill" is not a Naturalist or Determinist text — it is purely Realist in its concerns', '"To Build a Fire" is Determinist because of London\'s Naturalist philosophy; "The Mill" is about personal failure to adapt'], correct: 1, explanation: 'Both protagonists are destroyed by forces that don\'t know they exist. The cold doesn\'t know there is a man. The Industrial Revolution doesn\'t know there is a miller. Both forces operate by their own logic, indifferent to individual human presence. Naturalist determinism comes in multiple forms — natural and historical.' },
      { q: 'The wife in "The Mill" never speaks — she is depicted only through actions (walking home, finding the miller gone, walking toward the pond). What is the effect of her complete silence throughout the poem?', options: ['Robinson couldn\'t find an authentic voice for the wife\'s interior perspective', 'Her silence makes her grief universal — she becomes an Everywoman figure; more powerfully, her silence mirrors the poem\'s own refusal to state what has happened, showing rather than telling; the reader must infer her death exactly as she must infer her husband\'s', 'Her silence is a Realistic detail — women of this social class and period were often voiceless in their communities', 'Her silence creates suspense about what she will do next, driving the poem\'s tension forward'], correct: 1, explanation: 'The wife\'s silence is the poem\'s silence. Robinson doesn\'t tell us what happened to the miller; she doesn\'t know either. She must read the evidence — the cold tea, the dead fire, his absence — exactly as we must. Her wordlessness and the poem\'s wordlessness about the key events are the same technique.' },
      { q: 'A student reads "The Mill" and concludes: "The miller was weak — he should have learned a new trade when his became obsolete." How do Robinson\'s formal choices argue against this interpretation?', options: ['Robinson includes specific details showing the miller attempted to find other work but failed', 'Robinson presents the miller with no markers of personal weakness or laziness — the poem contains no evidence of failed will, only of failed economic conditions; his deliberate omission of personal fault forces the reader to locate the cause entirely in external circumstance; the form is Robinson\'s argument against victim-blaming', 'The student\'s reading is valid — the poem is genuinely ambiguous about whether the miller could have adapted', 'The miller\'s suicide suggests emotional fragility, which partially supports the weakness interpretation'], correct: 1, explanation: 'Robinson\'s most important formal choice: he gives the miller no flaws. No laziness, no incompetence, no missed warnings. The absence of personal fault in the poem is the argument. By removing all internal causes, Robinson leaves only the external — the mill becoming obsolete — as the explanation. The form forces the right reading.' }"""

# Inject into each work's questions array — add before the closing `]` of each
def inject_questions(content, topic_key, new_qs_str):
    # Find the closing pattern for this topic's questions array
    # Pattern: last question ends with `}`, then `\n    ]\n  },`
    # We need to find the specific topic block
    marker = f"  {topic_key}: {{\n"
    start = content.find(marker)
    if start == -1:
        print(f'MISS: topic {topic_key} not found')
        return content

    # Find the closing `    ]\n  },` after this marker
    # Look for the questions array closing bracket
    search_from = start
    # Find `    ]\n  },` or `    ]\n  }` (last topic)
    import re
    # Find end of questions array for this topic
    # The questions array ends with `      }\n    ]\n  }`
    pattern = r'      \}\n    \]\n  \}'
    m = re.search(pattern, content[search_from:])
    if not m:
        print(f'MISS: closing bracket not found for {topic_key}')
        return content

    insert_pos = search_from + m.start() + len('      }')
    insert_text = ',\n' + new_qs_str
    content = content[:insert_pos] + insert_text + content[insert_pos:]
    print(f'OK: {topic_key} questions added')
    return content

content = inject_questions(content, 'tbf', TBF_EXTRA)
content = inject_questions(content, 'tob', TOB_EXTRA)
content = inject_questions(content, 'dochill', DOCHILL_EXTRA)
content = inject_questions(content, 'abel', ABEL_EXTRA)
content = inject_questions(content, 'cory', CORY_EXTRA)
content = inject_questions(content, 'mill', MILL_EXTRA)

with open(r'C:/Users/Muhanad/Desktop/AS2_Revision/index.html', 'w', encoding='utf-8') as f:
    f.write(content)
print('Done')
